sudo: enabled
dist: xenial

language:
  - node_js
  - java

node_js:
  - "12"

# exclusive
branches: 
  only:
    - master
    - next

cache:
  directories:
    - "node_modules"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y ubuntu-restricted-extras
  - sudo apt-get install -y firefox
  - sudo apt-get install -y chromium-browser

install:
  - npm install

build:
  - npm run build

script:
  - npm run check:travis
  - sonar-scanner

addons:
  sonarcloud:
    organization: "rx-player"
    token:
      secure: "BmvFb3pXk9JzhitSmVj2YZ6wvhCIz7kymg6nU5aTWdCyOQMJgc62wWTJQtYc0Ndx+offeX4MgZetziQU9c7RcKE6cEh0/HL/k9nTiAdsgXBW2Lt8NLYSkbegtMrW2L82gDhrliFDfxzNX8KwTzjRY3+GglZDUSw0w1nAyRufeeKNNuCLRR/tBaEtKkgZN/U6t8MUvoqzt8GI5D4zZHuMn/yG4zo8YkaI6njgJglq0g8LSRPUhsTDH82rhuRZ8S2NNqehCM62dENdrhDL/6BEAA7gE1880tLQaPYwMbtWCF2EV//lFxUZECZp/zKd6HwminFdGbEWqDpapsSZUS7oPQRP0KEHr4UWgF/P2beVWUGalOA8hEKva8wRM2J5zJFiemqeRHlbcWf3pCpfhZzvoPvu8HHUFVQzSu159MrCthaF1zWfTMOHElcAMwtnOQBkIfoM0rCjvGPX10ERjkXylGkqfxyFDCrlZ6M09vVJgyjjU571GOwaqpUoACvNgJnmQTVO08efQD9zt8WvT2gxwx2n6mc0bOcXh2W5xaL3PsBh2YmN/JMOI37fDog1TERE8IImu7LXU+Sk7VTOiOylZj8nuR3Vvjjc36CWzwaUmxbXxbjUpZKgCfmSPbEUC78PKSHOIywbGsZLAudYWDhWY5cyXvWDcvE87cfbLM22zk0="
